// Global using directives

global using System;
global using System.Collections.Generic;
global using System.Data;
global using System.DirectoryServices;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq;
global using System.Reflection;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using System.Threading.Tasks;
global using Dapper;
global using DocumentFormat.OpenXml.Packaging;
global using DocumentFormat.OpenXml.Wordprocessing;
global using Helper.DataAccess.Dapper;
global using Helper.Extensions;
global using Helper.Security;
global using Helper.ApiCaller;
global using Helper.Cache.Redis;
global using Helper.Enums;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using Microsoft.IdentityModel.Tokens;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using OfficeOpenXml;
global using OfficeOpenXml.Style;
global using OfficeOpenXml.Table;
global using StackExchange.Redis;
global using TVSI.XTRADE.BO.API.Common;
global using TVSI.XTRADE.BO.API.Models.Dtos;
global using TVSI.XTRADE.BO.API.Models.Entities.Demo;
global using TVSI.XTRADE.BO.API.Models.Enums;
global using TVSI.XTRADE.BO.API.Models.Model;
global using TVSI.XTRADE.BO.API.Services.Interfaces;
global using TVSI.XTRADE.BO.API.Models.Model.Request.Bank;
global using TVSI.XTRADE.BO.API.Models.Model.Request.BankNo;
global using TVSI.XTRADE.BO.API.Models.Model.Request.InternalAccount;
global using TVSI.XTRADE.BO.API.Models.Model.Request.ManageOrder;
global using TVSI.XTRADE.BO.API.Models.Model.Request.SupperAccount;
global using TVSI.XTRADE.BO.API.Models.Model.Request.WhiteList;
global using TVSI.XTRADE.BO.API.Models.Model.Request.RightRegistration;
global using TVSI.XTRADE.BO.API.Models.Model.Response.APIPasiot;
global using TVSI.XTRADE.BO.API.Services.Interfaces.Business;
global using TVSI.XTRADE.BO.API.Services.Interfaces.Core;
global using Color = System.Drawing.Color;
global using Run = DocumentFormat.OpenXml.Wordprocessing.Run;
global using Table = DocumentFormat.OpenXml.Wordprocessing.Table;
global using Text = DocumentFormat.OpenXml.Wordprocessing.Text;